name: Publish to Nuget

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pack
      run: dotnet pack . --output nupkgs

    - name: Push to NuGet
      run: dotnet nuget push dotnet nuget push nupkgs/**.nupkg --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
      if: github.ref == 'refs/heads/master'