name: Publish to Nuget

on:
  workflow_call:
    secrets:
      nuget_api_key:
      required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Pack
      run: dotnet pack --no-build --output nupkgs

    - name: Push to NuGet
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
      if: github.ref == 'refs/heads/master'