name: Publish to Nuget

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Pack
      run: dotnet pack 

    - name: Push to NuGet
      run: dotnet nuget push .\My-Asp-NetCore-Web-Api-Template.1.0.1.nupkg --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
      if: github.ref == 'refs/heads/master'